modLoader="javafml"
loaderVersion="[${loaderversion},)"
issueTrackerURL="https://github.com/Elecs-Mods/E-Flux-2/issues"
authors="Elec332"

[[mods]]
modId="eflux2"
version="${version}"
displayName="E-Flux 2"
description="E-Flux 2"

[[dependencies.eflux2]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcversion},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.eflux2]]
    modId="forge"
    mandatory=true
    versionRange="[${forgeversion},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.eflux2]]
    modId="eleccore"
    mandatory=true
    versionRange="[${coreversion},)"
    ordering="AFTER"
    side="BOTH"
