modLoader="javafml"
loaderVersion="[${loaderversion},)"
issueTrackerURL="https://github.com/Elecs-Mods/E-Flux-2/issues"
displayURL="https://github.com/Elecs-Mods/E-Flux-2"
authors="Elec332"

[[mods]]
modId="eflux2"
version="${version}"
displayName="E-Flux2"
description="TODO"

[[dependencies.eflux2]]
    modId="eleccore"
    mandatory=true
    versionRange="[2.1.44-Beta,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.eflux2]]
    modId="forge"
    mandatory=true
    versionRange="[${forgeversion},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.eflux2]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mcversion},)"
    ordering="NONE"
    side="BOTH"
